http://apps.apple.com, 'NoneType' object has no attribute 'get_text'
http://api.whatsapp.com, 'NoneType' object has no attribute 'get_text'
http://qq.com, 'utf-8' codec can't decode byte 0xcc in position 53: invalid continuation byte
http://miit.gov.cn, HTTPConnectionPool(host='miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA99DB190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://macromedia.com, HTTPConnectionPool(host='macromedia.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA95FC6D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://baidu.com, ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
http://beian.miit.gov.cn, 'NoneType' object has no attribute 'get_text'
http://wixsite.com, HTTPConnectionPool(host='wixsite.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9594BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://vk.com, 'utf-8' codec can't decode byte 0xa0 in position 42030: invalid start byte
http://youtube-nocookie.com, HTTPSConnectionPool(host='youtube-nocookie.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'youtube-nocookie.com' doesn't match either of '*.google.com', '*.appengine.google.com', '*.bdn.dev', '*.origin-test.bdn.dev', '*.cloud.google.com', '*.crowdsource.google.com', '*.datacompute.google.com', '*.google.ca', '*.google.cl', '*.google.co.in', '*.google.co.jp', '*.google.co.uk', '*.google.com.ar', '*.google.com.au', '*.google.com.br', '*.google.com.co', '*.google.com.mx', '*.google.com.tr', '*.google.com.vn', '*.google.de', '*.google.es', '*.google.fr', '*.google.hu', '*.google.it', '*.google.nl', '*.google.pl', '*.google.pt', '*.googleadapis.com', '*.googleapis.cn', '*.googlevideo.com', '*.gstatic.cn', '*.gstatic-cn.com', 'googlecnapps.cn', '*.googlecnapps.cn', 'googleapps-cn.com', '*.googleapps-cn.com', 'gkecnapps.cn', '*.gkecnapps.cn', 'googledownloads.cn', '*.googledownloads.cn', 'recaptcha.net.cn', '*.recaptcha.net.cn', 'recaptcha-cn.net', '*.recaptcha-cn.net', 'widevine.cn', '*.widevine.cn', 'ampproject.org.cn', '*.ampproject.org.cn', 'ampproject.net.cn', '*.ampproject.net.cn', 'google-analytics-cn.com', '*.google-analytics-cn.com', 'googleadservices-cn.com', '*.googleadservices-cn.com', 'googlevads-cn.com', '*.googlevads-cn.com', 'googleapis-cn.com', '*.googleapis-cn.com', 'googleoptimize-cn.com', '*.googleoptimize-cn.com', 'doubleclick-cn.net', '*.doubleclick-cn.net', '*.fls.doubleclick-cn.net', '*.g.doubleclick-cn.net', 'doubleclick.cn', '*.doubleclick.cn', '*.fls.doubleclick.cn', '*.g.doubleclick.cn', 'dartsearch-cn.net', '*.dartsearch-cn.net', 'googletraveladservices-cn.com', '*.googletraveladservices-cn.com', 'googletagservices-cn.com', '*.googletagservices-cn.com', 'googletagmanager-cn.com', '*.googletagmanager-cn.com', 'googlesyndication-cn.com', '*.googlesyndication-cn.com', '*.safeframe.googlesyndication-cn.com', 'app-measurement-cn.com', '*.app-measurement-cn.com', 'gvt1-cn.com', '*.gvt1-cn.com', 'gvt2-cn.com', '*.gvt2-cn.com', '2mdn-cn.net', '*.2mdn-cn.net', 'googleflights-cn.net', '*.googleflights-cn.net', 'admob-cn.com', '*.admob-cn.com', 'googlesandbox-cn.com', '*.googlesandbox-cn.com', '*.gstatic.com', '*.metric.gstatic.com', '*.gvt1.com', '*.gcpcdn.gvt1.com', '*.gvt2.com', '*.gcp.gvt2.com', '*.url.google.com', '*.youtube-nocookie.com', '*.ytimg.com', 'android.com', '*.android.com', '*.flash.android.com', 'g.cn', '*.g.cn', 'g.co', '*.g.co', 'goo.gl', 'www.goo.gl', 'google-analytics.com', '*.google-analytics.com', 'google.com', 'googlecommerce.com', '*.googlecommerce.com', 'ggpht.cn', '*.ggpht.cn', 'urchin.com', '*.urchin.com', 'youtu.be', 'youtube.com', '*.youtube.com', 'youtubeeducation.com', '*.youtubeeducation.com', 'youtubekids.com', '*.youtubekids.com', 'yt.be', '*.yt.be', 'android.clients.google.com', 'developer.android.google.cn', 'developers.android.google.cn', 'source.android.google.cn'")))
http://oracle.com, HTTPSConnectionPool(host='oracle.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
http://list-manage.com, 'NoneType' object has no attribute 'get_text'
http://wpa.qq.com, 'NoneType' object has no attribute 'get_text'
http://msn.com, HTTPConnectionPool(host='msn.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA987E370>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://beian.gov.cn, HTTPConnectionPool(host='beian.gov.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9856DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://cloudfront.net, HTTPConnectionPool(host='cloudfront.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA95FEB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://i0.wp.com, 'NoneType' object has no attribute 'get_text'
http://mysql.com, HTTPSConnectionPool(host='mysql.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
http://bp.blogspot.com, HTTPConnectionPool(host='bp.blogspot.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABB42CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://googleusercontent.com, HTTPConnectionPool(host='googleusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA97AA100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://yelp.com, 'NoneType' object has no attribute 'get_text'
http://iso.org, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
http://www.beian.miit.gov.cn, HTTPConnectionPool(host='www.beian.miit.gov.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9C07F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://gouv.fr, HTTPConnectionPool(host='gouv.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9653FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://163.com, HTTPConnectionPool(host='163.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA97DDA60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://arcgis.com, 'content'
http://godaddy.com, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
http://sun.com, HTTPSConnectionPool(host='sun.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
http://web.whatsapp.com, 'NoneType' object has no attribute 'get_text'
http://or.kr, HTTPConnectionPool(host='or.kr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA98A3400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://yandex.ru, 'NoneType' object has no attribute 'get_text'
http://people.com.cn, 'utf-8' codec can't decode byte 0xc8 in position 341: invalid continuation byte
http://go.id, HTTPConnectionPool(host='go.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA95D8220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://azurewebsites.net, HTTPConnectionPool(host='azurewebsites.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA986C310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://microsoftonline.com, HTTPConnectionPool(host='microsoftonline.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA982E970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://eepurl.com, 'NoneType' object has no attribute 'get_text'
http://miitbeian.gov.cn, HTTPConnectionPool(host='miitbeian.gov.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9B87D60>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
http://bizjournals.com, 'NoneType' object has no attribute 'get_text'
http://i2.wp.com, 'NoneType' object has no attribute 'get_text'
http://gob.mx, HTTPConnectionPool(host='gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA90516D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://go.th, HTTPConnectionPool(host='go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA928AB20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://qc.ca, HTTPConnectionPool(host='qc.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7439610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://nyu.edu, 'content'
http://netscape.com, ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
http://barnesandnoble.com, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
http://govt.nz, HTTPConnectionPool(host='govt.nz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8F0D1C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://in.ua, HTTPConnectionPool(host='in.ua', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7585E20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://on.ca, HTTPConnectionPool(host='on.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9A1BB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://kiev.ua, HTTPConnectionPool(host='kiev.ua', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9757FA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://vkontakte.ru, 'utf-8' codec can't decode byte 0xa0 in position 42030: invalid start byte
http://amazon-adsystem.com, HTTPConnectionPool(host='amazon-adsystem.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA98B79A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://miibeian.gov.cn, HTTPConnectionPool(host='miibeian.gov.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA99D2F70>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
http://storage.googleapis.com, 'NoneType' object has no attribute 'get_text'
http://go.kr, HTTPConnectionPool(host='go.kr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA97AAD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://java.com, 'NoneType' object has no attribute 'get_text'
http://news.com.au, 'content'
http://bc.ca, HTTPConnectionPool(host='bc.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9D8D5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://uber.com, 'NoneType' object has no attribute 'get_text'
http://army.mil, HTTPConnectionPool(host='army.mil', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9AF1C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://twimg.com, HTTPConnectionPool(host='twimg.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA2B12B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://mapquest.com, 'NoneType' object has no attribute 'get_text'
http://web.dev, 'content'
http://gob.es, HTTPConnectionPool(host='gob.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA97E9AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://themegrill.com, HTTPConnectionPool(host='themegrill.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA751DA90>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
http://del.icio.us, HTTPSConnectionPool(host='del.icio.us', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1122)')))
http://navy.mil, HTTPConnectionPool(host='navy.mil', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA93B5C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://hyatt.com, 'NoneType' object has no attribute 'get_text'
http://netdna-ssl.com, 'NoneType' object has no attribute 'get_text'
http://gob.ar, HTTPConnectionPool(host='gob.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA54E130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://zillow.com, 'NoneType' object has no attribute 'get_text'
http://gv.at, HTTPConnectionPool(host='gv.at', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA748A790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://auctollo.com, 'NoneType' object has no attribute 'get_text'
http://securityfocus.com, HTTPConnectionPool(host='securityfocus.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9DDB310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://nic.in, HTTPConnectionPool(host='nic.in', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9DDB250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://sony.com, 'utf-8' codec can't decode byte 0x82 in position 665: invalid start byte
http://nhk.or.jp, HTTPConnectionPool(host='nhk.or.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9FD3760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://1drv.ms, 'NoneType' object has no attribute 'get_text'
http://or.id, HTTPConnectionPool(host='or.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8E48B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://lua.org, 'utf-8' codec can't decode byte 0xea in position 2017: invalid continuation byte
http://ups.com, HTTPConnectionPool(host='ups.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA69DD60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://metmuseum.org, 'NoneType' object has no attribute 'get_text'
http://yp.to, HTTPConnectionPool(host='yp.to', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9291910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://list-manage1.com, 'NoneType' object has no attribute 'get_text'
http://vatican.va, HTTPConnectionPool(host='vatican.va', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9B5B7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://tx.us, HTTPConnectionPool(host='tx.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAB9943A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://ed.ac.uk, HTTPConnectionPool(host='ed.ac.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9EEADF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://akamaihd.net, HTTPConnectionPool(host='akamaihd.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7455FA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://mn.us, HTTPConnectionPool(host='mn.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA967C3A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://dropboxusercontent.com, HTTPConnectionPool(host='dropboxusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA90503D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://gwu.edu, HTTPConnectionPool(host='gwu.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9CF4BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://toutiao.com, 'NoneType' object has no attribute 'get_text'
http://gob.pe, HTTPConnectionPool(host='gob.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9249880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://af.mil, HTTPConnectionPool(host='af.mil', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9251A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://asso.fr, HTTPConnectionPool(host='asso.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8EF8580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://or.th, HTTPConnectionPool(host='or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABC90400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://unfccc.int, 'NoneType' object has no attribute 'get_text'
http://urldefense.com, HTTPConnectionPool(host='urldefense.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9B39280>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://hbs.edu, HTTPConnectionPool(host='hbs.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8EEAE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://envato.market, HTTPConnectionPool(host='envato.market', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA92898E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://cwi.nl, HTTPConnectionPool(host='cwi.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA90C5D30>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://staticflickr.com, HTTPConnectionPool(host='staticflickr.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9875B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://filesusr.com, HTTPConnectionPool(host='filesusr.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7455400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://ca.us, HTTPConnectionPool(host='ca.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA743F610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://penguinrandomhouse.com, 'NoneType' object has no attribute 'get_text'
http://gpo.gov, 'content'
http://iso.ch, HTTPSConnectionPool(host='iso.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'iso.ch' doesn't match either of 'www.iso.org', 'iso.org'")))
http://linksynergy.com, HTTPConnectionPool(host='linksynergy.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA912B730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://ahajournals.org, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
http://ec-lyon.fr, HTTPConnectionPool(host='ec-lyon.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7544BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://githubusercontent.com, HTTPConnectionPool(host='githubusercontent.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9EA35E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://campaign-archive.com, 'NoneType' object has no attribute 'get_text'
http://brightcove.net, 'NoneType' object has no attribute 'get_text'
http://epicgames.com, 'NoneType' object has no attribute 'get_text'
http://in.th, HTTPConnectionPool(host='in.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9AF3250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://jiathis.com, HTTPConnectionPool(host='jiathis.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA97F83A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://faa.gov, HTTPConnectionPool(host='faa.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABA25820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://lin.ee, 'NoneType' object has no attribute 'get_text'
http://unam.mx, HTTPConnectionPool(host='unam.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA4E6A60>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
http://waw.pl, HTTPConnectionPool(host='waw.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9875E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://fl.us, HTTPConnectionPool(host='fl.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8E2BFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://bluehost.com, 'content'
http://cdninstagram.com, HTTPConnectionPool(host='cdninstagram.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9B39AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://rsasecurity.com, HTTPConnectionPool(host='rsasecurity.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA1C0AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://chat.whatsapp.com, 'NoneType' object has no attribute 'get_text'
http://fastcgi.com, HTTPConnectionPool(host='fastcgi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8F28A00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://modsecurity.org, 'NoneType' object has no attribute 'get_text'
http://hexun.com, 'utf-8' codec can't decode byte 0xb2 in position 64: invalid start byte
http://nj.us, HTTPConnectionPool(host='nj.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9AA94C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://sch.id, HTTPConnectionPool(host='sch.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8F918B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://elmundo.es, 'utf-8' codec can't decode byte 0xed in position 384: invalid continuation byte
http://ny.us, HTTPConnectionPool(host='ny.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA931C3A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://wassenaar.org, HTTPConnectionPool(host='wassenaar.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA92FADF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://freetds.org, HTTPConnectionPool(host='freetds.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9CF89A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://specbench.org, HTTPConnectionPool(host='specbench.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8E1F190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://wixstatic.com, HTTPConnectionPool(host='wixstatic.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA952C9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://mhlw.go.jp, HTTPConnectionPool(host='mhlw.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA74F3E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://corriere.it, 'utf-8' codec can't decode byte 0xec in position 86655: invalid continuation byte
http://apachetutor.org, HTTPConnectionPool(host='apachetutor.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA362190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://blogs.com, 'content'
http://iplanet.com, HTTPConnectionPool(host='iplanet.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9AA4520>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://ywspj.com, HTTPConnectionPool(host='ywspj.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA005100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://jst.go.jp, HTTPConnectionPool(host='jst.go.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA94E5070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://chromium.org, 'NoneType' object has no attribute 'get_text'
http://pa.us, HTTPConnectionPool(host='pa.us', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9468460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://gingerall.com, HTTPConnectionPool(host='gingerall.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA74E1430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://hud.gov, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
http://alicdn.com, HTTPConnectionPool(host='alicdn.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABDC6820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://golux.com, HTTPConnectionPool(host='golux.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA90C2910>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://netperf.org, HTTPConnectionPool(host='netperf.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7477400>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://ohio.gov, HTTPConnectionPool(host='ohio.gov', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAB9957C0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
http://cloudwaysapps.com, HTTPConnectionPool(host='cloudwaysapps.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9E81DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://wto.org, ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
http://apachetoday.com, 'utf-8' codec can't decode byte 0xa0 in position 60649: invalid start byte
http://tsinghua.edu.cn, HTTPConnectionPool(host='tsinghua.edu.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA90C5970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://docs.aws.amazon.com, 'NoneType' object has no attribute 'get_text'
http://u-tokyo.ac.jp, HTTPConnectionPool(host='u-tokyo.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABBD3820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://aap.org, 'content'
http://ezinearticles.com, HTTPConnectionPool(host='ezinearticles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9312250>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
http://threebit.net, HTTPConnectionPool(host='threebit.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9CF6DF0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
http://ebscohost.com, HTTPSConnectionPool(host='ebscohost.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'ebscohost.com' doesn't match either of '*.ebsco.com', 'ebsco.com'")))
http://comcast.net, HTTPConnectionPool(host='comcast.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA90EE2B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://web.id, HTTPConnectionPool(host='web.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA8ED4B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://ytimg.com, HTTPConnectionPool(host='ytimg.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9CF8C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://anrdoezrs.net, HTTPConnectionPool(host='anrdoezrs.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAA6A0B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://demon.co.uk, HTTPConnectionPool(host='demon.co.uk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABA35880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://azureedge.net, HTTPConnectionPool(host='azureedge.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA98CF9A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://nationalacademies.org, 'NoneType' object has no attribute 'get_text'
http://rtve.es, 'utf-8' codec can't decode byte 0xfa in position 3889: invalid start byte
http://wikispaces.com, HTTPConnectionPool(host='wikispaces.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9258160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://storify.com, HTTPConnectionPool(host='storify.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AAB8FD730>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
http://artnet.com, 'NoneType' object has no attribute 'get_text'
http://mcusercontent.com, 'NoneType' object has no attribute 'get_text'
http://grigorik.com, HTTPConnectionPool(host='grigorik.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA7429910>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
http://livedoor.jp, HTTPConnectionPool(host='livedoor.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9B733D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://helpguide.org, HTTPConnectionPool(host='helpguide.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AABB67B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://marca.com, 'utf-8' codec can't decode byte 0xed in position 5311: invalid continuation byte
http://kqzyfj.com, HTTPConnectionPool(host='kqzyfj.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9D30820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
http://esy.es, HTTPConnectionPool(host='esy.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9D30910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
http://jimdosite.com, HTTPConnectionPool(host='jimdosite.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021AA9E755B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
